loglevel: INFO

paths:
  proxy_path_root: R:/ProxyMedia

proxy_settings:
  vid_codec: dnxhd
  h_res: 1280 
  v_res: 720
  vid_profile: dnxhr_sq 
  pix_fmt: yuv422p
  audio:
    audio_codec: pcm_s16le
    audio_samplerate: 48000
  misc_args: [-hide_banner, -stats, -loglevel error]
  ext: .mxf

filters:
  acceptable_exts : [.mov, .mp4, .mxf, .avi]

celery_settings:

  # REQUIRED - User details:

  host_address: 192.168.1.19
  broker_url:  redis://192.168.1.19:6379/0
  flower_url: http://192.168.1.19:5555
  result_backend: redis://192.168.1.19:6379/0

  # REQUIRED - User preference:

  result_expires: 60 # 10 mins
  worker_concurrency: 1
  worker_prefetch_multiplier: 1
  worker_max_tasks_per_child: 1
  worker_use_win_terminal: True
  worker_start_minimized: True
  