debug: true

rabbit_mq:
  user: marco
  password: yolo
  address: 192.168.1.19
  vhost: marco_vhost
  protocol: amqp
  backend: rpc://
  
paths:
  proxy_path_root: "R:\\ProxyMedia"
  ffmpeg: "C:\\Program Files\\FFMPEG"
  revision_sep: "_"

proxy_settings:
  vid_codec: dnxhd
  h_res: 1280 
  v_res: 720
  vid_profile: dnxhr_sq 
  pix_fmt: yuv422p
  audio:
    audio_codec: pcm_s16le
    audio_samplerate: 48000
  misc_args: [-hide_banner, -stats, -loglevel error]
  ext: .mxf
  overwrite_mode: increment #keep, skip

filters:
  acceptable_exts : [.mov, .mp4, .mxf, .avi]