name: poetry export requirements.txt

on:
  push:

jobs:
  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Export requirements
      uses: DivideProjects/poetry-export-requirements-action@v1
      with:
        without-hashes: true
        outfile-name: requirements.txt

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build: Export updated requirements.txt"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
